package com.test.cashi.domain.model

import kotlinx.serialization.Serializable
import kotlin.math.absoluteValue
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

/**
 * Represents a payment transaction
 * @property id Unique identifier for the transaction (generated by Firebase)
 * @property recipientEmail Email address of the payment recipient
 * @property amount Payment amount (must be > 0)
 * @property currency Currency code (USD or EUR)
 * @property timestamp Unix timestamp in milliseconds when payment was created
 * @property status Current status of the payment
 */
@Serializable
data class Payment @OptIn(ExperimentalTime::class) constructor(
    val id: String = "",
    val recipientEmail: String,
    val amount: Double,
    val currency: Currency,
    val timestamp: Long = Clock.System.now().toEpochMilliseconds(),
    val status: TransactionStatus = TransactionStatus.PENDING
) {
    /**
     * Formats the payment amount with currency symbol
     */
    fun formattedAmount(): String {
        // Convert to cents first to avoid floating-point issues
        val cents = kotlin.math.round(amount * 100).toLong()
        val dollars = cents / 100
        val remainingCents = (cents % 100).absoluteValue

        return "${currency.symbol}$dollars.${remainingCents.toString().padStart(2, '0')}"
    }
}

/**
 * Request model for creating a new payment (without id and timestamp)
 */
@Serializable
data class PaymentRequest(
    val recipientEmail: String,
    val amount: Double,
    val currency: Currency
)

/**
 * Response model from the payment API
 */
@Serializable
data class PaymentResponse(
    val success: Boolean,
    val payment: Payment? = null,
    val error: String? = null
)